version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/"
      - "/examples/packaged/packages/report-task"
      - "/examples/packaged/packages/summary-task"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
