[build-system]
requires = ["setuptools>=84.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gwflow"
version = "0.4.0"
description = "Task definitions for gwf workflows"
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = {file = "LICENSE"}
dependencies = ["gwf==2.1.1"]

[project.entry-points."gwf.plugins"]
run = "gwflow.run:run"
explain = "gwflow.explain:explain"
status = "gwflow.status:status"
clean-work = "gwflow.clean_work:clean_work"

[tool.setuptools.packages.find]
where = ["src"]
