{% set name = "gwflow" %}
{% set version = "0.5.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.12,<3.13
    - pip
    - setuptools >=84
  run:
    - python >=3.12,<3.13
    - gwf ==2.1.1
    - rich >=15.0.0,<16

test:
  imports:
    - gwflow
  commands:
    - gwf --version

about:
  summary: Task definitions for gwf workflows
  license: MIT
  license_file: LICENSE
